name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.x"
      - run: npm ci
      - run: npm run format:check
      - run: npm run test-headless--code-coverage
        env:
          CI: true
